import turtle as t
import time
window = t.Screen()
window.bgpic("sprite/background.gif")
window.title("A Game Made By Boris")
t.register_shape("sprite/player.gif")
t.register_shape("sprite/player2.gif")
t.register_shape("sprite/player3.gif")
t.register_shape("sprite/fire1.gif")
t.register_shape("sprite/fire2.gif")
t.register_shape("sprite/fire3.gif")
t.register_shape("sprite/fire4.gif")
t.register_shape("sprite/alien.gif")
t.register_shape("sprite/alien2.gif")
t.register_shape("sprite/alien3.gif")
t.register_shape("sprite/bomb.gif")
t.register_shape("sprite/explosion.gif")
t.register_shape("sprite/explosion2.gif")
t.register_shape("sprite/explosion3.gif")
t.register_shape("sprite/explosion4.gif")
t.register_shape("sprite/explosion5.gif")
t.register_shape("sprite/explosion6.gif")
t.register_shape("sprite/explosion7.gif")
t.register_shape("sprite/explosion8.gif")
t.register_shape("sprite/explosion9.gif")
t.register_shape("sprite/explosion10.gif")
t.register_shape("sprite/rocket.gif")
player = t.Turtle()
player.shape("sprite/player.gif")
player_is = "ALIVE"
player.x = 0
player.y = 0
player.penup()
player.setposition(0,50)
fire = t.Turtle()
fire.shape("sprite/fire1.gif")
fire.penup()
fire.setposition(0,-40)
rocket = t.Turtle()
rocket.hideturtle()
rocket.shape("sprite/rocket.gif")
rocket.penup()
rocket.setposition(200,0)
enemy = t.Turtle()
enemy.hideturtle()
enemy.shape("sprite/alien.gif")
enemy.penup()
enemy.setposition(0,350)
enemy.showturtle()
bomb = t.Turtle()
bomb.hideturtle()
bomb.penup()
bomb.x = enemy.xcor()
bomb.y = enemy.ycor()
bomb.shape("sprite/bomb.gif")
bomb.setposition(enemy.xcor(),enemy.ycor())
def jeter_bombe():
    bomb.showturtle()
    bomb.setposition(player.x,player.y)
    bomb.shape("sprite/explosion.gif")
    time.sleep(0.1)
    bomb.shape("sprite/explosion2.gif")
    time.sleep(0.1)
    bomb.shape("sprite/explosion3.gif")
    time.sleep(0.1)
    bomb.shape("sprite/explosion4.gif")
    time.sleep(0.1)
    bomb.shape("sprite/explosion5.gif")
    time.sleep(0.1)
    bomb.shape("sprite/explosion6.gif")
    time.sleep(0.1)
    bomb.shape("sprite/explosion7.gif")
    time.sleep(0.1)
    bomb.shape("sprite/explosion8.gif")
    time.sleep(0.1)
    bomb.shape("sprite/explosion9.gif")
    time.sleep(0.1)
    bomb.shape("sprite/explosion10.gif")
    time.sleep(0.1)
    bomb.hideturtle()
    bomb.setposition(enemy.xcor(),enemy.ycor())
    bomb.shape("sprite/bomb.gif")
jeter_bombe()
ex = enemy.xcor()
ey = enemy.ycor()
player.shape("sprite/player.gif")
fire.hideturtle()
time.sleep(0.1)
player.shape("sprite/player3.gif")
for i in range(10):
    player.y -= 1
    player.sety(player.y)
enemy.setx(player.x)
for i in range(10):
    enemy.shape("sprite/alien.gif")
    time.sleep(0.1)
    enemy.shape("sprite/alien2.gif")
    time.sleep(0.1)
    enemy.shape("sprite/alien3.gif")
    ey -= 30
    enemy.sety(ey)
for i in range(10):
    enemy.shape("sprite/alien.gif")
    time.sleep(0.1)
    enemy.shape("sprite/alien2.gif")
    time.sleep(0.1)
    enemy.shape("sprite/alien3.gif")
    ey += 10
    player.y += 10
    enemy.sety(ey)
    player.sety(player.y)
rocket.showturtle()
rocket.setposition(ex + 50,ey)
time.sleep(0.1)
rocket.shape("sprite/explosion.gif")
rocket.setx(ex)
time.sleep(0.1)
rocket.shape("sprite/explosion2.gif")
time.sleep(0.1)
ex -= 30
enemy.setx(ex)
rocket.shape("sprite/explosion3.gif")
time.sleep(0.1)
ex -= 40
enemy.setx(ex)
rocket.shape("sprite/explosion4.gif")
time.sleep(0.1)
ex -= 50
enemy.setx(ex)
rocket.shape("sprite/explosion5.gif")
time.sleep(0.1)
ex -= 60
enemy.setx(ex)
rocket.shape("sprite/explosion6.gif")
time.sleep(0.1)
ex -= 70
enemy.setx(ex)
rocket.shape("sprite/explosion7.gif")
time.sleep(0.1)
ex -= 80
enemy.setx(ex)
rocket.shape("sprite/explosion8.gif")
time.sleep(0.1)
ex -= 90
enemy.setx(ex)
rocket.shape("sprite/explosion9.gif")
time.sleep(0.1)
ex -= 100
enemy.setx(ex)
rocket.shape("sprite/explosion10.gif")
time.sleep(0.1)
ex -= 110
enemy.setx(ex)
rocket.hideturtle()
for i in range(10):
    player.y -= 10
    player.sety(player.y)
player.shape("sprite/player.gif")
time.sleep(0.1)
player.setposition(0,10)
fire.showturtle()
time.sleep(0.1)
player.setposition(0,50)
def right():
    player.x += 10
    player.shape("sprite/player.gif")
    player.setx(player.x)
    fire.setx(player.x)
    if player.x == 510:
        print("Chapitre 2")
def left():
    player.x -= 10
    player.shape("sprite/player2.gif")
    player.setx(player.x)
    fire.setx(player.x)
t.listen()
t.onkey(right,"Right")
t.onkey(left,"Left")
while True:
    if player.x == 510:
        print("chapitre 2")
    enemy.shape("sprite/alien.gif")
    time.sleep(0.1)
    enemy.shape("sprite/alien2.gif")
    time.sleep(0.1)
    enemy.shape("sprite/alien3.gif")
    time.sleep(0.1)
    fire.shape("sprite/fire1.gif")
    time.sleep(0.1)
    fire.shape("sprite/fire2.gif")
    time.sleep(0.1)
    fire.shape("sprite/fire3.gif")
    time.sleep(0.1)
    fire.shape("sprite/fire4.gif")
    time.sleep(0.1)


